/*
* generated by Xtext
*/
package org.example.mongoemf.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.example.mongoemf.services.SQLQueryGrammarAccess;

public class SQLQueryParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SQLQueryGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.example.mongoemf.parser.antlr.internal.InternalSQLQueryParser createParser(XtextTokenStream stream) {
		return new org.example.mongoemf.parser.antlr.internal.InternalSQLQueryParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public SQLQueryGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SQLQueryGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
