/*
* generated by Xtext
*/
package org.example.mongoemf.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SQLQueryAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/example/mongoemf/parser/antlr/internal/InternalSQLQuery.tokens");
	}
}
