/*
* generated by Xtext
*/
package org.eclipselabs.mongo.query.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class MongoSQLOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
