/*
* generated by Xtext
*/
package org.example.mongoemf.ui.contentassist;

import org.example.mongoemf.ui.contentassist.AbstractSQLQueryProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SQLQueryProposalProvider extends AbstractSQLQueryProposalProvider {

}
