/*
 * generated by Xtext
 */
package org.eclipselabs.mongo.query.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MongoSQLUiModule extends org.eclipselabs.mongo.query.ui.AbstractMongoSQLUiModule {
	public MongoSQLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
