/*
 * generated by Xtext
 */
package org.example.mongoemf.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SQLQueryExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.example.mongoemf.ui.internal.SQLQueryActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.example.mongoemf.ui.internal.SQLQueryActivator.getInstance().getInjector("org.example.mongoemf.SQLQuery");
	}
	
}
