/*
* generated by Xtext
*/
package org.example.mongoemf.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class SQLQueryOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
