/*
 * generated by Xtext
 */
package org.example.mongoemf;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SQLQueryRuntimeModule extends org.example.mongoemf.AbstractSQLQueryRuntimeModule {

}
