/*
* generated by Xtext
*/
package org.eclipselabs.mongo.query;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MongoSQLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.eclipselabs.mongo.query.ui.internal.MongoSQLActivator.getInstance().getInjector("org.eclipselabs.mongo.query.MongoSQL");
	}
	
}
