/*
* generated by Xtext
*/
package org.example.mongoemf;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SQLQueryUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.example.mongoemf.ui.internal.SQLQueryActivator.getInstance().getInjector("org.example.mongoemf.SQLQuery");
	}
	
}
