/*
* generated by Xtext
*/
package org.eclipselabs.mongo.query.ui.contentassist;

import org.eclipselabs.mongo.query.ui.contentassist.AbstractMongoSQLProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class MongoSQLProposalProvider extends AbstractMongoSQLProposalProvider {

}
