/*
 * generated by Xtext
 */
package org.example.mongoemf.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SQLQueryUiModule extends org.example.mongoemf.ui.AbstractSQLQueryUiModule {
	public SQLQueryUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
